const express = require('express');
const cors = require('cors');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 3001;
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// === TICKER VALIDATION ===
const validTickers = ['AAPL','MSFT','GOOGL','GOOG','AMZN','NVDA','META','TSLA','BRK.B','UNH','JNJ','V','XOM','WMT','JPM','MA','PG','AVGO','HD','CVX','MRK','ABBV','LLY','PEP','KO','COST','ADBE','CRM','AMD','NFLX','TMO','ACN','MCD','CSCO','ABT','DHR','TXN','NEE','UPS','PM','INTC','HON','LOW','UNP','AMGN','IBM','BA','GE','CAT','SBUX','GS','BLK','ISRG','MDLZ','ADI','REGN','VRTX','GILD','BKNG','ADP','MMC','SYK','LRCX','SCHW','CB','ZTS','TMUS','MO','PLD','CI','SO','DUK','BDX','CME','CL','ICE','AON','BSX','SHW','FIS','NOC','LMT','RTX','GD','HII','PYPL','SQ','SHOP','COIN','MARA','RIOT','PLTR','SNOW','CRWD','NET','DDOG','ZS','OKTA','MDB','RIVN','NIO','LI','XPEV','LCID','F','GM','TM','DIS','WBD','PARA','CMCSA','SNAP','PINS','RBLX','ARM','SMCI','DELL','HPQ','ORCL','NOW','PANW','TSM','ASML','QCOM','MRVL','MU','KLAC','AMAT','BAC','MS','WFC','C','USB','PNC','TFC','PFE','MRNA','BMY','AZN','NVO','SNY','CVS','WBA','HCA','ELV','COP','SLB','OXY','EOG','DVN','HAL','BABA','JD','PDD','BIDU','TCEHY','NKE','LULU','TJX','ROST','UBER','LYFT','ABNB','DASH','AI','BBAI','SOUN','UPST','PATH','SOFI','HOOD','LC','NU','ENPH','SEDG','FSLR','RUN','SPY','QQQ','IWM','DIA','VOO','GLD','SLV','USO','TLT'];

function levenshtein(a,b){const m=a.length,n=b.length,dp=Array.from({length:m+1},()=>Array(n+1).fill(0));for(let i=0;i<=m;i++)dp[i][0]=i;for(let j=0;j<=n;j++)dp[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(a[i-1]!==b[j-1]?1:0));return dp[m][n]}
function similarity(a,b){if(a===b)return 1;const l=a.length>b.length?a:b,s=a.length>b.length?b:a;if(!l.length)return 1;let bonus=0;for(let i=0;i<Math.min(a.length,b.length);i++){if(a[i]===b[i])bonus+=.15;else break}if(l.includes(s)||s.includes(l))bonus+=.3;return Math.min(1,(l.length-levenshtein(a,b))/l.length+bonus)}
app.post('/api/validate-ticker',(req,res)=>{const u=(req.body.ticker||'').toUpperCase().trim();if(validTickers.includes(u))return res.json({valid:true,ticker:u,suggestions:[]});const s=validTickers.map(t=>({ticker:t,score:similarity(u,t)})).filter(t=>t.score>.4).sort((a,b)=>b.score-a.score).slice(0,5).map(t=>t.ticker);res.json({valid:false,ticker:u,suggestions:s})});

// === SECTOR MAP ===
const sectorMap={'AAPL':{sector:'tech',related:['MSFT','GOOGL'],themes:['스마트폰','AI','클라우드']},'MSFT':{sector:'tech',related:['AAPL','GOOGL','CRM'],themes:['클라우드','AI','엔터프라이즈']},'GOOGL':{sector:'tech',related:['META','MSFT','AMZN'],themes:['검색','AI','광고']},'META':{sector:'tech',related:['GOOGL','SNAP','PINS'],themes:['소셜미디어','AI','메타버스']},'NVDA':{sector:'semiconductor',related:['AMD','INTC','TSM','AVGO','SMCI'],themes:['AI칩','GPU','데이터센터']},'AMD':{sector:'semiconductor',related:['NVDA','INTC','TSM'],themes:['CPU','GPU','데이터센터']},'INTC':{sector:'semiconductor',related:['NVDA','AMD','TSM'],themes:['반도체','파운드리','PC']},'TSM':{sector:'semiconductor',related:['NVDA','AMD','ASML'],themes:['파운드리','반도체 제조','AI칩']},'AVGO':{sector:'semiconductor',related:['NVDA','QCOM','TXN'],themes:['네트워킹','반도체','AI']},'TSLA':{sector:'ev',related:['RIVN','NIO','LI','F','LCID'],themes:['전기차','자율주행','배터리']},'RIVN':{sector:'ev',related:['TSLA','LCID','F'],themes:['전기차','EV 트럭','생산']},'NIO':{sector:'ev',related:['TSLA','LI','XPEV'],themes:['중국 전기차','배터리 교환','EV']},'AMZN':{sector:'ecommerce',related:['SHOP','WMT','BABA'],themes:['이커머스','AWS','물류']},'NFLX':{sector:'entertainment',related:['DIS','WBD','PARA'],themes:['스트리밍','콘텐츠','구독']},'JPM':{sector:'finance',related:['BAC','GS','MS','WFC'],themes:['은행','금리','투자은행']},'GS':{sector:'finance',related:['JPM','MS','BAC'],themes:['투자은행','M&A','트레이딩']},'XOM':{sector:'energy',related:['CVX','COP','SLB'],themes:['석유','에너지','정유']},'PLTR':{sector:'ai_software',related:['AI','SNOW','CRWD'],themes:['AI 분석','정부 계약','빅데이터']},'COIN':{sector:'crypto',related:['MARA','RIOT','HOOD'],themes:['암호화폐','거래소','비트코인']},'BA':{sector:'defense',related:['LMT','RTX','NOC','GD'],themes:['방산','항공','우주']}};
const sectorNames={ko:{tech:'빅테크',semiconductor:'반도체',ev:'전기차',ecommerce:'이커머스',entertainment:'엔터테인먼트',finance:'금융',healthcare:'헬스케어',energy:'에너지',ai_software:'AI 소프트웨어',crypto:'암호화폐',fintech:'핀테크',defense:'방산'},en:{tech:'Big Tech',semiconductor:'Semiconductors',ev:'EV',ecommerce:'E-Commerce',entertainment:'Entertainment',finance:'Finance',healthcare:'Healthcare',energy:'Energy',ai_software:'AI Software',crypto:'Crypto',fintech:'Fintech',defense:'Defense'}};

// === DATE UTILS ===
function genDate(hAgo){const d=new Date();d.setHours(d.getHours()-hAgo);return d.toISOString()}
function fmtTime(iso,lang){const now=new Date(),d=new Date(iso),h=Math.floor((now-d)/36e5),dd=Math.floor((now-d)/864e5);if(h<1)return lang==='ko'?'방금':'Just now';if(h<24)return lang==='ko'?`${h}시간 전`:`${h}h ago`;if(dd<7)return lang==='ko'?`${dd}일 전`:`${dd}d ago`;return d.toLocaleDateString(lang==='ko'?'ko-KR':'en-US',{month:'short',day:'numeric'})}
function fmtDate(iso,lang){return new Date(iso).toLocaleDateString(lang==='ko'?'ko-KR':'en-US',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function pickRandom(a,n){return[...a].sort(()=>Math.random()-.5).slice(0,Math.min(n,a.length))}

// === NEWS ENDPOINT ===
app.post('/api/news',(req,res)=>{
  const{tickers,language}=req.body;
  try{
    const lang=language==='ko'?'ko':'en';
    let news=generateAllNews(tickers,lang);
    news.sort((a,b)=>{
      if(a.tier==='breaking'&&b.tier!=='breaking')return -1;
      if(b.tier==='breaking'&&a.tier!=='breaking')return 1;
      if(a.tier==='core'&&b.tier!=='core'&&b.tier!=='breaking')return -1;
      if(b.tier==='core'&&a.tier!=='core'&&a.tier!=='breaking')return 1;
      return new Date(b.date)-new Date(a.date);
    });
    news=news.map(n=>({...n,time:fmtTime(n.date,lang),dateFormatted:fmtDate(n.date,lang)}));
    res.json({success:true,news});
  }catch(e){res.status(500).json({success:false,error:e.message})}
});

function generateAllNews(t,l){return[...genBreaking(l),...genCore(t,l),...genRelated(t,l),...genMarket(l),...genFed(l),...genPolitics(l),...genUSChina(l),...genGeo(l),...genCrypto(l),...genTech(l),...genCommodities(l),...genEarnings(l),...genTrending(t,l)]}

// === TIER 0: BREAKING ===
function genBreaking(lang){
  const T={ko:[
    {t:"🚨 연준, 긴급 금리 0.5%p 인하",c:"연방준비제도가 긴급 FOMC를 소집해 금리를 0.5%p 인하했습니다. 경기 침체 대응으로 시장 전반에 큰 파장이 예상됩니다.",i:"positive"},
    {t:"🚨 트럼프, 중국산 전 품목 60% 관세 서명",c:"중국산 모든 수입품에 60% 관세를 부과하는 행정명령이 서명되었습니다. 글로벌 무역 질서에 근본적 변화가 시작됩니다.",i:"negative"},
    {t:"🚨 중국 AI '시던스 2.0' 공개, GPT-5 능가 주장",c:"중국 AI 기업이 GPT-5를 뛰어넘는다고 주장하는 모델을 공개했습니다. 미국 AI 우위에 대한 재평가가 시작되고 있습니다.",i:"negative"},
    {t:"🚨 미국 CPI 급등, 인플레이션 재발 공포",c:"CPI가 전월 대비 0.8% 급등하며 인플레이션 공포가 확산되고 있습니다. 금리 인상 재개 가능성이 부각됩니다.",i:"negative"},
    {t:"🚨 S&P 500 하루 5% 급락, 서킷브레이커 발동",c:"경기 침체와 지정학적 리스크가 겹치며 S&P 500이 5% 급락, 거래가 일시 중단되었습니다.",i:"negative"},
    {t:"🚨 NVDA, DOJ 반독점 소송 제기",c:"법무부가 엔비디아를 AI 칩 독점 혐의로 소송했습니다. AI 산업 구조 변화가 예상됩니다.",i:"negative"},
    {t:"🚨 비트코인 15만 달러 돌파, 사상 최고",c:"비트코인이 15만 달러를 돌파하며 사상 최고치를 경신했습니다. 기관 매수세가 가격을 견인하고 있습니다.",i:"positive"},
    {t:"🚨 대만 해협 군사 충돌 위기, 글로벌 패닉",c:"대만 해협에서 미중 군사 긴장이 극도로 고조되며 TSM이 20% 이상 급락했습니다.",i:"negative"},
  ],en:[
    {t:"🚨 Fed Cuts Rates 0.5% in Emergency",c:"The Fed convened an emergency FOMC and cut rates by 50bps. Markets bracing for major shockwaves.",i:"positive"},
    {t:"🚨 Trump Signs 60% Tariff on All Chinese Imports",c:"Executive order imposing 60% tariffs on all Chinese imports signed. Fundamental trade shift underway.",i:"negative"},
    {t:"🚨 China's 'Cidence 2.0' Claims to Beat GPT-5",c:"A Chinese AI firm unveiled a model claiming to surpass GPT-5. US AI dominance reassessment begins.",i:"negative"},
    {t:"🚨 US CPI Spikes, Inflation Fears Return",c:"CPI surged 0.8% MoM. Markets tumbling as rate hike fears resurface.",i:"negative"},
    {t:"🚨 S&P 500 Crashes 5%, Circuit Breakers Hit",c:"Recession fears and geopolitical risks sent S&P down 5%. Circuit breakers triggered.",i:"negative"},
    {t:"🚨 DOJ Sues NVDA for AI Chip Monopoly",c:"DOJ filed antitrust suit against Nvidia. AI industry structural changes expected.",i:"negative"},
    {t:"🚨 Bitcoin Breaks $150K All-Time High",c:"Bitcoin surged past $150K. Institutional buying and ETF inflows driving the rally.",i:"positive"},
    {t:"🚨 Taiwan Strait Crisis Sparks Global Panic",c:"US-China military tensions at extreme levels. TSM crashed 20%+ on supply chain fears.",i:"negative"},
  ]};
  return pickRandom(T[lang],3).map((item,i)=>({title:item.t,content:item.c,ticker:lang==='ko'?'⚡ 속보':'⚡ BREAKING',source:['Reuters FLASH','Bloomberg URGENT','AP Breaking','CNBC Alert'][i%4],date:genDate(Math.floor(Math.random()*3)),impact:item.i,tier:'breaking',tierLabel:lang==='ko'?'🚨 속보':'🚨 BREAKING'}));
}

// === TIER 1: CORE ===
function genCore(tickers,lang){
  const T={ko:{p:[{t:"{t} 실적 발표 후 급등",c:"{t}가 예상을 뛰어넘는 실적을 발표했습니다."},{t:"{t} 신제품으로 기대감 고조",c:"{t}가 혁신적인 신제품을 공개했습니다."},{t:"{t} CEO 낙관적 전망",c:"{t} CEO가 성장에 자신감을 표명했습니다."},{t:"{t} 자사주 매입 발표",c:"{t}가 대규모 자사주 매입을 발표했습니다."},{t:"{t} 목표가 상향",c:"증권사들이 {t} 목표가를 상향했습니다."},{t:"{t} AI 사업 확대",c:"{t}가 AI 투자를 단행하고 있습니다."}],n:[{t:"{t} 규제 우려 하락",c:"{t}가 규제 이슈로 하락 중입니다."},{t:"{t} 실적 기대 하회",c:"{t} 실적이 예상을 밑돌았습니다."},{t:"{t} 마진 압박",c:"{t}가 경쟁으로 수익성 우려가 커졌습니다."},{t:"{t} 내부자 매도",c:"{t} 경영진 매도가 알려졌습니다."},{t:"{t} 소송 리스크",c:"{t}가 소송에 휘말렸습니다."}]},en:{p:[{t:"{t} Surges on Earnings",c:"{t} beat Wall Street expectations."},{t:"{t} New Product Excites",c:"{t} unveiled breakthrough innovation."},{t:"{t} CEO Bullish",c:"{t}'s CEO confident on growth."},{t:"{t} Major Buyback",c:"{t} announced significant buyback."},{t:"{t} Targets Raised",c:"Brokerages raised {t} targets."},{t:"{t} AI Expansion",c:"{t} investing heavily in AI."}],n:[{t:"{t} Falls on Regulation",c:"{t} hit by regulatory concerns."},{t:"{t} Misses Estimates",c:"{t} results below expectations."},{t:"{t} Margin Pressure",c:"{t} facing competitive pressure."},{t:"{t} Insider Selling",c:"Insider selling reported at {t}."},{t:"{t} Litigation Risk",c:"{t} facing major lawsuit."}]}};
  const news=[];
  tickers.forEach((ticker,idx)=>{const num=Math.random()>.3?2:3;const used=new Set();for(let i=0;i<num;i++){const s=Math.random()>.35?'p':'n';let ti;do{ti=Math.floor(Math.random()*T[lang][s].length)}while(used.has(`${s}${ti}`)&&used.size<T[lang][s].length);used.add(`${s}${ti}`);const tmpl=T[lang][s][ti];news.push({title:tmpl.t.replace(/{t}/g,ticker),content:tmpl.c.replace(/{t}/g,ticker),ticker,source:['Reuters','Bloomberg','CNBC','MarketWatch','WSJ'][idx%5],date:genDate(Math.floor(Math.random()*48)+1),impact:s==='p'?'positive':'negative',tier:'core',tierLabel:lang==='ko'?'📌 내 종목':'📌 My Stocks'})}});
  return news;
}

// === TIER 2: RELATED ===
function genRelated(tickers,lang){
  const T={ko:["{sector}, {theme} 수요 증가 — {rt} 수혜 기대","{rt}, {theme} 경쟁력 강화 — 시장 주목","{sector} ETF 자금 유입 — {rt} 강세","{rt} {theme} 신기술 — 업계 주목","{sector} 전망 긍정 — {rt} 개선 기대"],en:["{sector} Gains on {theme} — {rt} benefiting","{rt} Strengthens in {theme}","{sector} ETFs See Inflows — {rt} strong","{rt} New {theme} Tech — Attention","{sector} Outlook Bullish — {rt} improving"]};
  const news=[],usedT=new Set(tickers),sectors=new Set();
  tickers.forEach(ticker=>{const info=sectorMap[ticker];if(info&&!sectors.has(info.sector)){sectors.add(info.sector);info.related.filter(t=>!usedT.has(t)).slice(0,3).forEach(rt=>{usedT.add(rt);const tmpl=T[lang][Math.floor(Math.random()*T[lang].length)];const theme=info.themes[Math.floor(Math.random()*info.themes.length)];const sn=sectorNames[lang][info.sector]||info.sector;const filled=tmpl.replace(/{sector}/g,sn).replace(/{rt}/g,rt).replace(/{theme}/g,theme);const parts=filled.split(' — ');news.push({title:parts[0],content:parts[1]||parts[0],ticker:rt,source:['Reuters','Bloomberg','FT',"Barron's",'Seeking Alpha'][Math.floor(Math.random()*5)],date:genDate(Math.floor(Math.random()*72)+6),impact:Math.random()>.3?'positive':'neutral',tier:'related',tierLabel:lang==='ko'?`🔗 관련 · ${sn}`:`🔗 Related · ${sn}`})})}});
  return news;
}

// === TIER 3+: ALL OTHER TIERS ===
function mkNews(T,lang,count,ticker,tier,tierLabel,sources,hRange){
  return pickRandom(T[lang],count).map((item,i)=>({title:item.t,content:item.c,ticker:typeof ticker==='function'?ticker(lang):ticker,source:sources[i%sources.length],date:genDate(Math.floor(Math.random()*((hRange||[2,96])[1]-(hRange||[2,96])[0]))+(hRange||[2,96])[0]),impact:item.i||'neutral',tier,tierLabel:typeof tierLabel==='function'?tierLabel(lang):tierLabel}));
}

function genMarket(l){return mkNews({ko:[{t:"S&P 500 최고치 후 조정",c:"차익 실현 매물이 나오고 있습니다."},{t:"나스닥 1% 상승",c:"기술주 강세에 1% 올랐습니다."},{t:"다우 혼조세",c:"방어주 중심 혼조세입니다."},{t:"VIX 20 돌파",c:"시장 불안감이 커지고 있습니다."},{t:"증시 관망세",c:"지표 발표 앞두고 관망 중입니다."},{t:"연착륙 전망 우세",c:"투자은행들이 연착륙에 무게를 두고 있습니다."},{t:"옵션 만기 변동성",c:"옵션 만기를 앞두고 변동성이 커졌습니다."},{t:"소비 심리 하락",c:"소비 심리가 3개월 연속 하락했습니다."}],en:[{t:"S&P Pulls Back After Record",c:"Profit-taking after record high."},{t:"Nasdaq Up 1%+",c:"Tech strength lifted Nasdaq."},{t:"Dow Mixed",c:"Rotation into defensives."},{t:"VIX Above 20",c:"Rising market anxiety."},{t:"Markets Await Data",c:"Cautious ahead of data."},{t:"Soft Landing Expected",c:"Banks betting on soft landing."},{t:"Options Expiry Vol",c:"Volatility on expiry."},{t:"Sentiment Down",c:"Consumer sentiment fell again."}]},l,8,x=>x==='ko'?'시장':'Market','market',x=>x==='ko'?'🌍 시장':'🌍 Market',['Bloomberg','FT','WSJ','Reuters','AP','CNBC','MarketWatch',"Barron's"])}

function genFed(l){return mkNews({ko:[{t:"연준 금리 인하 서두르지 않겠다",c:"파월이 인하를 서두르지 않겠다고 밝혔습니다."},{t:"10년물 4.5% 돌파",c:"국채 수익률이 4.5%를 넘었습니다."},{t:"연내 인하 가능성 시사",c:"연준 위원이 연내 인하 가능성을 언급했습니다."},{t:"페드워치 9월 인하 60%",c:"9월 인하 확률이 60%를 넘었습니다."},{t:"CPI 둔화 신호",c:"CPI가 예상을 하회했습니다."},{t:"FOMC 의견 분열",c:"회의록에서 의견 차이가 확인되었습니다."},{t:"PPI 상승",c:"PPI가 예상을 상회했습니다."},{t:"고용 견고",c:"고용이 예상을 상회했습니다."}],en:[{t:"Fed: No Rush to Cut",c:"Powell reiterated patience."},{t:"10Y Breaks 4.5%",c:"Yield surged past 4.5%."},{t:"Fed Hints Cut This Year",c:"Governor suggested possible cut."},{t:"FedWatch: 60% Sept",c:"60%+ September cut probability."},{t:"CPI Cools",c:"CPI below expectations."},{t:"FOMC Divided",c:"Minutes show disagreement."},{t:"PPI Up",c:"PPI exceeded expectations."},{t:"Jobs Strong",c:"Payrolls beat estimates."}]},l,8,x=>x==='ko'?'금리':'Rates','fed',x=>x==='ko'?'🏦 금리·연준':'🏦 Fed & Rates',['Bloomberg','Reuters','WSJ','CNBC','FT','AP','MarketWatch',"Barron's"])}

function genPolitics(l){return mkNews({ko:[{t:"반도체 보조금 2차 배분",c:"2차 보조금 계획이 발표되었습니다."},{t:"빅테크 규제 심의",c:"독점 규제 심의에 착수했습니다."},{t:"대선 경제가 핵심",c:"경제 정책이 최대 관심사입니다."},{t:"트럼프 관세 강화",c:"관세 인상을 시사했습니다."},{t:"SEC 암호화폐 규제",c:"새 규제가 발표되었습니다."},{t:"AI 규제 행정명령",c:"AI 안전성 명령이 발표되었습니다."},{t:"셧다운 우려",c:"셧다운 가능성이 부각 중입니다."},{t:"방산 예산 최대",c:"최대 방산 예산이 추진 중입니다."},{t:"FTC M&A 강화",c:"M&A 심사가 강화됩니다."},{t:"EV 보조금 강화",c:"EV 세금 공제 요건이 강화되었습니다."}],en:[{t:"CHIPS 2nd Round",c:"Second subsidy round announced."},{t:"Big Tech Regulation",c:"Antitrust hearings started."},{t:"Economy Top Issue",c:"Economy is top voter concern."},{t:"Trump Tariff Signal",c:"Higher tariffs signaled."},{t:"SEC Crypto Rules",c:"New crypto framework."},{t:"AI Regulation Order",c:"AI safety order issued."},{t:"Shutdown Fears",c:"Budget talks stalled."},{t:"Record Defense Budget",c:"Largest defense budget pushed."},{t:"FTC M&A Rules",c:"Stricter merger review."},{t:"EV Credit Tightened",c:"Stricter EV eligibility."}]},l,10,x=>x==='ko'?'정치':'Politics','politics',x=>x==='ko'?'🏛️ 정치':'🏛️ Politics',['Politico','AP','Reuters','WSJ','WashPost','CNN','Bloomberg','Hill','NYT','NPR'])}

function genUSChina(l){return mkNews({ko:[{t:"AI 칩 규제 강화",c:"중국 대상 AI 칩 규제가 강화되었습니다."},{t:"희토류 수출 제한",c:"희토류 수출 제한이 발표되었습니다."},{t:"딥시크 AI 우위 위협",c:"저비용 고성능 AI 모델이 공개되었습니다."},{t:"화웨이 자체 칩 서버",c:"자체 칩 AI 서버가 출시되었습니다."},{t:"공급망 재편 가속",c:"공급망 재편이 가속화 중입니다."},{t:"중국 EV 유럽 확대",c:"BYD가 유럽 시장을 확대하고 있습니다."},{t:"바이오 투자 제한",c:"바이오테크 투자 제한 검토 중입니다."},{t:"대만 해협 긴장",c:"반도체 리스크가 부각 중입니다."},{t:"중국 경제 둔화",c:"성장률 하락 우려가 커지고 있습니다."},{t:"양자컴퓨터 경쟁",c:"양자 분야로 경쟁이 확산 중입니다."}],en:[{t:"AI Chip Controls Tightened",c:"Further restrictions to China."},{t:"Rare Earth Limits",c:"Export restrictions announced."},{t:"DeepSeek AI Threat",c:"High-performance model unveiled."},{t:"Huawei Own-Chip Server",c:"Self-developed chip servers launched."},{t:"Supply Chain Shift",c:"Restructuring accelerating."},{t:"Chinese EVs in Europe",c:"BYD gaining market share."},{t:"Biotech Limits Reviewed",c:"Investment restrictions under review."},{t:"Taiwan Tensions",c:"Chip supply risks highlighted."},{t:"China Slowdown",c:"Growth below expectations."},{t:"Quantum Race",c:"Rivalry enters quantum computing."}]},l,10,x=>x==='ko'?'미중':'US-China','uschina',x=>x==='ko'?'🇺🇸🇨🇳 미중':'🇺🇸🇨🇳 US-China',['Reuters','Bloomberg','SCMP','Nikkei','WSJ','FT','AP','CNN','Diplomat','Politico'])}

function genGeo(l){return mkNews({ko:[{t:"중동 유가 급등",c:"지정학적 긴장으로 유가가 올랐습니다."},{t:"우크라이나 에너지 위기",c:"에너지 안보 우려가 커지고 있습니다."},{t:"NATO 방위비 증액",c:"방위비 3%까지 증액 합의했습니다."},{t:"엔화 약세 지속",c:"환율 전쟁 우려가 나옵니다."},{t:"인도 제조 허브",c:"인도가 제조업 허브로 부상 중입니다."},{t:"식량 가격 상승",c:"식량 가격이 오르고 있습니다."},{t:"OPEC+ 감산 연장",c:"감산이 연장되었습니다."},{t:"홍해 해운비 급등",c:"해운 비용이 급등 중입니다."}],en:[{t:"Middle East Oil Surge",c:"Tensions driving oil higher."},{t:"Ukraine Energy Crisis",c:"Energy concerns reviving."},{t:"NATO Defense Boost",c:"3% GDP defense agreed."},{t:"Yen Weakness",c:"Currency war fears."},{t:"India Manufacturing",c:"India as new hub."},{t:"Food Prices Up",c:"Climate driving prices."},{t:"OPEC+ Cuts Extended",c:"Production cuts extended."},{t:"Red Sea Shipping Spike",c:"Shipping costs surging."}]},l,8,x=>x==='ko'?'지정학':'Geopolitics','geopolitics',x=>x==='ko'?'🌐 지정학':'🌐 Geopolitics',['Reuters','Bloomberg','BBC','Al Jazeera','FT','AP','DW','Nikkei'])}

function genCrypto(l){return mkNews({ko:[{t:"비트코인 10만불 후 조정",c:"차익 실현 조정 중입니다.",i:'neutral'},{t:"이더리움 ETF 기대",c:"ETF 기대에 상승 중입니다.",i:'positive'},{t:"스테이블코인 법안 임박",c:"규제 법안이 통과를 앞두고 있습니다."},{t:"채굴 수익성 분화",c:"반감기 후 수익성이 갈리고 있습니다."},{t:"기관 암호화폐 확대",c:"기관들이 비중을 늘리고 있습니다.",i:'positive'},{t:"DeFi TVL 최고",c:"DeFi TVL이 최고치입니다.",i:'positive'}],en:[{t:"BTC Corrects After $100K",c:"Profit-taking pullback.",i:'neutral'},{t:"ETH ETF Hopes",c:"ETF expectations rising.",i:'positive'},{t:"Stablecoin Bill Near",c:"Regulation approaching vote."},{t:"Mining Diverges",c:"Post-halving profitability varies."},{t:"Institutions Boost Crypto",c:"Increasing allocations.",i:'positive'},{t:"DeFi TVL Record",c:"All-time high TVL.",i:'positive'}]},l,6,x=>x==='ko'?'암호화폐':'Crypto','crypto',x=>x==='ko'?'₿ 암호화폐':'₿ Crypto',['CoinDesk','The Block','Decrypt','Bloomberg','CoinTelegraph','Messari'])}

function genTech(l){return mkNews({ko:[{t:"GPT-5 공개 임박",c:"오픈AI가 GPT-5를 준비 중입니다.",i:'positive'},{t:"AI 투자 2000억불",c:"글로벌 AI 투자가 급증하고 있습니다.",i:'positive'},{t:"비전 프로 2세대",c:"애플이 2세대를 개발 중입니다.",i:'positive'},{t:"자율주행 레벨4",c:"레벨4 상용화가 근접했습니다.",i:'positive'},{t:"양자컴퓨터 실용화",c:"실용적 사례가 발표되었습니다.",i:'positive'},{t:"AI 에이전트 시대",c:"업무 자동화가 혁명 중입니다.",i:'positive'},{t:"데이터센터 전력 문제",c:"전력 부족이 대두 중입니다."},{t:"휴머노이드 로봇",c:"로봇 기업들이 성장 중입니다.",i:'positive'}],en:[{t:"GPT-5 Imminent",c:"OpenAI preparing launch.",i:'positive'},{t:"AI Investment $200B+",c:"Global AI spending surging.",i:'positive'},{t:"Vision Pro 2",c:"Apple developing next-gen.",i:'positive'},{t:"Level 4 Driving Near",c:"Approaching commercialization.",i:'positive'},{t:"Quantum Practical",c:"Practical applications shown.",i:'positive'},{t:"AI Agent Era",c:"Transforming workflows.",i:'positive'},{t:"Data Center Power",c:"Power becoming constraint."},{t:"Humanoid Robots",c:"Companies growing fast.",i:'positive'}]},l,8,x=>x==='ko'?'테크':'Tech','techtrends',x=>x==='ko'?'🚀 테크':'🚀 Tech Trends',['TechCrunch','Verge','Wired','Ars','MIT Review','Bloomberg','Reuters','CNBC'])}

function genCommodities(l){return mkNews({ko:[{t:"금 사상 최고 근접",c:"금 가격이 오르고 있습니다."},{t:"유가 85달러",c:"중동 긴장으로 유가가 올랐습니다."},{t:"구리 급등 AI 수요",c:"데이터센터 구리 수요가 급증 중입니다."},{t:"리튬 반등",c:"EV 수요 회복 기대입니다."},{t:"천연가스 상승",c:"겨울 수요로 가격이 올랐습니다."},{t:"은 동반 상승",c:"금과 함께 은도 오르고 있습니다."}],en:[{t:"Gold Nears Record",c:"Uncertainty driving gold."},{t:"Oil at $85",c:"Middle East tensions."},{t:"Copper on AI Demand",c:"Data center demand."},{t:"Lithium Rebounds",c:"EV demand recovery."},{t:"Natural Gas Up",c:"Winter demand outlook."},{t:"Silver Rallies",c:"Rising with gold."}]},l,6,x=>x==='ko'?'원자재':'Commodities','commodities',x=>x==='ko'?'⛏️ 원자재':'⛏️ Commodities',['Bloomberg','Reuters','Kitco','OilPrice','Mining.com','S&P Global'])}

function genEarnings(l){return mkNews({ko:[{t:"S&P 75% 예상 상회",c:"기업 75%가 예상을 넘었습니다.",i:'positive'},{t:"빅테크 실적 주간",c:"빅테크 실적이 예정되어 있습니다."},{t:"은행 실적 호조",c:"은행들이 금리 수혜를 확인했습니다.",i:'positive'},{t:"소비재 둔화",c:"소비재 실적이 부진합니다.",i:'negative'},{t:"AI 기업 가이던스 상향",c:"AI 기업들이 가이던스를 올렸습니다.",i:'positive'},{t:"헬스케어 안정",c:"헬스케어가 방어주 역할 중입니다."}],en:[{t:"75% S&P Beat",c:"Three-quarters beat estimates.",i:'positive'},{t:"Big Tech Week",c:"Major earnings expected."},{t:"Banks Strong",c:"Rate benefits confirmed.",i:'positive'},{t:"Consumer Slow",c:"Spending concerns rising.",i:'negative'},{t:"AI Guidance Up",c:"AI companies raising outlook.",i:'positive'},{t:"Healthcare Steady",c:"Defensive earnings stable."}]},l,6,x=>x==='ko'?'실적':'Earnings','earnings',x=>x==='ko'?'📊 실적':'📊 Earnings',['Bloomberg','Reuters','CNBC','MarketWatch',"Barron's",'Seeking Alpha'])}

function genTrending(tickers,l){
  const T={ko:[{ticker:'PLTR',t:"PLTR 정부 계약 급증",c:"정부 계약을 수주했습니다.",i:'positive'},{ticker:'COIN',t:"COIN 비트코인 동반 급등",c:"암호화폐 강세에 급등했습니다.",i:'positive'},{ticker:'SMCI',t:"SMCI AI 서버 급등",c:"AI 서버 수요로 급등했습니다.",i:'positive'},{ticker:'SOFI',t:"SOFI 성장 가속",c:"사업 다각화로 성장 중입니다.",i:'positive'},{ticker:'ARM',t:"ARM AI 칩 수혜",c:"AI 칩 수요 수혜를 받고 있습니다.",i:'positive'},{ticker:'CRWD',t:"CRWD 사이버보안 급증",c:"보안 투자 확대로 성장 중입니다.",i:'positive'},{ticker:'SNOW',t:"SNOW 클라우드 확대",c:"클라우드 입지를 강화 중입니다.",i:'positive'},{ticker:'UBER',t:"UBER 자율주행 파트너십",c:"자율주행 파트너십을 체결했습니다.",i:'positive'},{ticker:'AI',t:"C3.ai AI 수요 급등",c:"기업용 AI 수요가 급증했습니다.",i:'positive'},{ticker:'MARA',t:"MARA 채굴 효율 개선",c:"채굴 효율을 크게 개선했습니다.",i:'positive'}],en:[{ticker:'PLTR',t:"PLTR Gov Contract Surge",c:"Major contract win.",i:'positive'},{ticker:'COIN',t:"COIN Rallies with BTC",c:"Crypto rally lifts stock.",i:'positive'},{ticker:'SMCI',t:"SMCI AI Server Jump",c:"AI demand surge.",i:'positive'},{ticker:'SOFI',t:"SOFI Growth Accelerates",c:"Banking license driving growth.",i:'positive'},{ticker:'ARM',t:"ARM AI Chip Benefit",c:"Royalty boost from AI.",i:'positive'},{ticker:'CRWD',t:"CRWD Cybersecurity Boom",c:"Security spending surge.",i:'positive'},{ticker:'SNOW',t:"SNOW Cloud Expansion",c:"Platform growth continues.",i:'positive'},{ticker:'UBER',t:"UBER Autonomous Deal",c:"Self-driving partnership.",i:'positive'},{ticker:'AI',t:"C3.ai Enterprise Demand",c:"AI solution demand booming.",i:'positive'},{ticker:'MARA',t:"MARA Mining Gains",c:"Efficiency improvements.",i:'positive'}]};
  return pickRandom(T[l].filter(x=>!tickers.includes(x.ticker)),8).map((item,i)=>({title:item.t,content:item.c,ticker:item.ticker,source:['Reddit','WSB','Seeking Alpha','Benzinga','TipRanks','Motley Fool','Stocktwits','Finviz'][i%8],date:genDate(Math.floor(Math.random()*48)+2),impact:item.i,tier:'trending',tierLabel:l==='ko'?'🔥 트렌딩':'🔥 Trending'}));
}

// SPA fallback
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`✅ Stock News running on port ${PORT}`));
